name: sbc-turingrk1

on:
  workflow_dispatch:
  push:
    branches: [ 'release-*' ]
    tags:
      - "v*"
env:
  REGISTRY: registry.camsab.me:443
  USER: "talos"
jobs:
  sbc:
    runs-on: home-runners

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # need history for `git describe` to work for Talos `Makefile`
          fetch-depth: 0
          fetch-tags: true
      - name: Install make
        run: sudo apt-get update && sudo apt-get install make
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."docker-registry.registry.svc.cluster.local:5000"]
              http = true
            [worker.oci]
            gc = true
            gckeepstorage = 50000
          
            [[worker.oci.gcpolicy]]
              keepBytes = 10737418240
              keepDuration = 604800
              filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
            [[worker.oci.gcpolicy]]
              all = true
              keepBytes = 53687091200
          driver: kubernetes
          driver-opts: |
            namespace=actions-runner
            replicas=1
            nodeselector=model=rk1
            limits.memory=2G
            limits.ephemeral-storage=2G

      - name: Build and push sbc turingrk1 overlay image
        run: make
        env:
          PUSH: '1'
          PLATFORM: linux/arm64
          PROGRESS: plain
          CI_ARGS: "--cache-from=${{ env.REGISTRY }}/${{ env.USER }}/sbc-turingrk1:cache --cache-to=${{ env.REGISTRY }}/${{ env.USER }}/sbc-turingrk1:cache"

